### ISSUE TITLE
More size than expected is required

### ISSUE THREAD

**Issue by PabloBotas** [foundation29org/RareCrowds#1]
Just wanted to note that the data currently containing 68597 in PublicCases (private repo) needs a size of ~400 Mb, not the 50 initially estimated. This size may go up if more data is included in the phenopacket files.

FYI @hchittanuru3

**Comment by PabloBotas** [comment]
There is a hard limit of 2Gb total repo size. We're going to hit that limit as soon as we change something in the phenopackets.

Need a solution for this...

**Comment by hchittanuru3** [comment]
Can we host the data somewhere else?

**Comment by PabloBotas** [comment]
@Alvaromah can we dedicate a resource group for this?

**Comment by hchittanuru3** [comment]
Currently hosting data on Azure

**Comment by PabloBotas** [comment]
Great!!
