### ISSUE TITLE
The line data = dann.data['ORPHA:324'] does not retrieve the expected results

### ISSUE THREAD

**Issue by AtoanyFierro** [foundation29org/RareCrowds#15]
**When I run this lines:**

from rarecrowds import DiseaseAnnotations
dann = DiseaseAnnotations(mode='intersect')
data = dann.data['ORPHA:324']
print(data)

**I do not get the following desirable information:**

data = {
    'ageDeath': ['adult'],
    'ageOnset': ['Childhood'],
    'group': 'Disorder',
    'inheritance': ['X-linked recessive'],
    'link': 'http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=324',
    'name': 'Fabry disease',
    'phenotype': {   'HP:0000083': {   'frequency': 'HP:0040281',
                                       'modifier': {   'diagnosticCriteria': True}},
                     'HP:0000091': {   'frequency': 'HP:0040282',
                                       'modifier': {   'diagnosticCriteria': True}},
                     ## Many other symptoms here
                     'HP:0100820': {   'frequency': 'HP:0040283',
                                       'modifier': {   'diagnosticCriteria': True}}},
    'prevalence': [   {   'class': '1-9 / 1 000 000',
                          'geographic': 'Europe',
                          'meanPrev': '0.22',
                          'qualification': 'Value and class',
                          'source': 'ORPHANET',
                          'type': 'Prevalence at birth',
                          'validation': {'status': 'Not yet validated'}},
                      ## Other prevalence studies here
                      {   'class': '1-9 / 100 000',
                          'geographic': 'Sweden',
                          'meanPrev': '1.11',
                          'qualification': 'Value and class',
                          'source': '25274184[PMID]',
                          'type': 'Prevalence at birth',
                          'validation': {'status': 'Validated'}}],
    'source': {},
    'type': 'Disease',
    'validation': {'date': '2016-06-01 00:00:00.0', 'status': 'y'}
}

**What it is retrieved is the following:**

{'name': 'Fabry disease', 'phenotype': {'HP:0000083': {'Frequency': 'HP:0040281'}, 'HP:0000091': {'Frequency': 'HP:0040282'}, 'HP:0000093': {'Frequency': 'HP:0040282'}, 'HP:0000100': {'Frequency': 'HP:0040281'}, 'HP:0000112': {'Frequency': 'HP:0040282'}, 'HP:0000179': {'Frequency': 'HP:0040282'}, 'HP:0000280': {'Frequency': 'HP:0040282'}, 'HP:0000365': {'Frequency': 'HP:0040281'}, 'HP:0000407': {'Frequency': 'HP:0040283'}, 'HP:0000518': {'Frequency': 'HP:0040282'}, 'HP:0000524': {'Frequency': 'HP:0040281'}, 'HP:0000648': {'Frequency': 'HP:0040282'}, 'HP:0000708': {'Frequency': 'HP:0040282'}, 'HP:0000716': {'Frequency': 'HP:0040283'}, 'HP:0000739': {'Frequency': 'HP:0040283'}, 'HP:0000790': {'Frequency': 'HP:0040281'}, 'HP:0000822': {'Frequency': 'HP:0040283'}, 'HP:0000823': {'Frequency': 'HP:0040282'}, 'HP:0000873': {'Frequency': 'HP:0040283'}, 'HP:0000962': {'Frequency': 'HP:0040281'}, 'HP:0000966': {'Frequency': 'HP:0040281'}, 'HP:0001004': {'Frequency': 'HP:0040283'}, 'HP:0001014': {'Frequency': 'HP:0040281'}, 'HP:0001131': {'Frequency': 'HP:0040281'}, 'HP:0001250': {'Frequency': 'HP:0040283'}, 'HP:0001369': {'Frequency': 'HP:0040281'}, 'HP:0001482': {'Frequency': 'HP:0040281'}, 'HP:0001635': {'Frequency': 'HP:0040281'}, 'HP:0001637': {'Frequency': 'HP:0040283'}, 'HP:0001639': {'Frequency': 'HP:0040283'}, 'HP:0001646': {'Frequency': 'HP:0040282'}, 'HP:0001653': {'Frequency': 'HP:0040282'}, 'HP:0001678': {'Frequency': 'HP:0040282'}, 'HP:0001681': {'Frequency': 'HP:0040283'}, 'HP:0001712': {'Frequency': 'HP:0040283'}, 'HP:0001903': {'Frequency': 'HP:0040281'}, 'HP:0001945': {'Frequency': 'HP:0040283'}, 'HP:0002017': {'Frequency': 'HP:0040282'}, 'HP:0002024': {'Frequency': 'HP:0040281'}, 'HP:0002027': {'Frequency': 'HP:0040281'}, 'HP:0002039': {'Frequency': 'HP:0040282'}, 'HP:0002093': {'Frequency': 'HP:0040283'}, 'HP:0002094': {'Frequency': 'HP:0040283'}, 'HP:0002097': {'Frequency': 'HP:0040282'}, 'HP:0002321': {'Frequency': 'HP:0040283'}, 'HP:0002326': {'Frequency': 'HP:0040281'}, 'HP:0002376': {'Frequency': 'HP:0040283'}, 'HP:0002571': {'Frequency': 'HP:0040283'}, 'HP:0002823': {'Frequency': 'HP:0040283'}, 'HP:0002829': {'Frequency': 'HP:0040281'}, 'HP:0003077': {'Frequency': 'HP:0040282'}, 'HP:0003119': {'Frequency': 'HP:0040282'}, 'HP:0003326': {'Frequency': 'HP:0040281'}, 'HP:0004306': {'Frequency': 'HP:0040283'}, 'HP:0004322': {'Frequency': 'HP:0040282'}, 'HP:0004349': {'Frequency': 'HP:0040283'}, 'HP:0006510': {'Frequency': 'HP:0040283'}, 'HP:0007957': {'Frequency': 'HP:0040281'}, 'HP:0011675': {'Frequency': 'HP:0040283'}, 'HP:0011710': {'Frequency': 'HP:0040282'}, 'HP:0012378': {'Frequency': 'HP:0040281'}, 'HP:0100543': {'Frequency': 'HP:0040282'}, 'HP:0100579': {'Frequency': 'HP:0040281'}, 'HP:0100585': {'Frequency': 'HP:0040281'}, 'HP:0100820': {'Frequency': 'HP:0040283'}}}

**How can I get the expected output?**

**Comment by PabloBotas** [comment]
There was a bug in principle solved by commit 14ccaad96bd3c05c51248fa547ceb5b6538bce40. This has to be fully tested, but if you are comfortable you may directly use the code from the repo, not the package. You should retrieve the original information this way.

**Comment by PabloBotas** [comment]
@hchittanuru3, I think I solved this one, but I could not test it yet. Please, if you have time could you verify that the output matches the README? Thanks!!

**Comment by AtoanyFierro** [comment]
Solved, thank you

**Comment by PabloBotas** [comment]
Great, we'll push these changes to the official release as soon as we can ;)

**Comment by hchittanuru3** [comment]
Hey @AtoanyFierro this bug should be resolved in the new release - [0.0.5](https://pypi.org/project/rarecrowds/).

Please let me know if this doesn't work - I will keep this issue open for a while.
